// Generated by Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
#ifndef FORMSENGINE_SWIFT_H
#define FORMSENGINE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FormsEngine",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
@class SODataEntityDefault;
@class SODataV4_EntityValue;

SWIFT_CLASS("_TtC11FormsEngine23ApproverMasterDataModel")
@interface ApproverMasterDataModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull UserSystemID;
@property (nonatomic, copy) NSString * _Nonnull PersonnelNum;
@property (nonatomic, copy) NSString * _Nonnull EmailID;
@property (nonatomic) BOOL Active;
@property (nonatomic, copy) NSString * _Nonnull FirstName;
@property (nonatomic, copy) NSString * _Nonnull LastName;
@property (nonatomic, copy) NSString * _Nonnull Contact;
@property (nonatomic, copy) NSString * _Nonnull DepartmentID;
@property (nonatomic, copy) NSString * _Nonnull DepartmentName;
@property (nonatomic, copy) NSString * _Nonnull ApproverRole;
@property (nonatomic, copy) NSString * _Nonnull ApproverLevel;
@property (nonatomic, copy) NSString * _Nonnull Plant;
@property (nonatomic, copy) NSString * _Nonnull WorkCenter;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine19DeptMasterDataModel")
@interface DeptMasterDataModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull DepartmentID;
@property (nonatomic, copy) NSString * _Nonnull DepartmentName;
@property (nonatomic, copy) NSString * _Nonnull Plant;
@property (nonatomic) BOOL Active;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine15FEOfflineHelper")
@interface FEOfflineHelper : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;
@class SODataDuration;

SWIFT_CLASS("_TtC11FormsEngine19FormAssignDataModel")
@interface FormAssignDataModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull FormID;
@property (nonatomic, copy) NSString * _Nonnull Version;
@property (nonatomic, copy) NSString * _Nonnull OrderType;
@property (nonatomic, copy) NSString * _Nonnull ControlKey;
@property (nonatomic, copy) NSString * _Nonnull TaskListType;
@property (nonatomic, copy) NSString * _Nonnull Group;
@property (nonatomic, copy) NSString * _Nonnull GroupCounter;
@property (nonatomic, copy) NSString * _Nonnull InternalCounter;
@property (nonatomic, copy) NSString * _Nonnull EquipCategory;
@property (nonatomic, copy) NSString * _Nonnull FuncLocCategory;
@property (nonatomic, copy) NSString * _Nonnull Category;
@property (nonatomic, copy) NSString * _Nonnull JobType;
@property (nonatomic, copy) NSString * _Nonnull Mandatory;
@property (nonatomic, copy) NSString * _Nonnull FlowSequence;
@property (nonatomic, copy) NSString * _Nonnull MultipleSub;
@property (nonatomic, copy) NSString * _Nonnull Occur;
@property (nonatomic, copy) NSString * _Nonnull Theme;
@property (nonatomic, copy) NSString * _Nonnull Stylesheet;
@property (nonatomic, copy) NSDate * _Nullable CreatedOn;
@property (nonatomic, copy) NSString * _Nonnull CreatedBy;
@property (nonatomic, copy) NSDate * _Nullable ModifiedOn;
@property (nonatomic, copy) NSString * _Nonnull ModifiedBy;
@property (nonatomic) NSInteger filledFormCount;
@property (nonatomic, copy) NSString * _Nonnull FormAssignmentType;
@property (nonatomic, copy) NSString * _Nonnull WorkOrderNum;
@property (nonatomic, copy) NSString * _Nonnull OprNum;
@property (nonatomic, copy) NSString * _Nonnull FormCategory;
@property (nonatomic) BOOL PostNotification;
@property (nonatomic, copy) NSDate * _Nullable AssignedDate;
@property (nonatomic, strong) SODataDuration * _Nonnull AssignedTime;
@property (nonatomic, copy) NSString * _Nonnull AssignedBy;
@property (nonatomic, copy) NSString * _Nonnull Notification;
@property (nonatomic, copy) NSString * _Nonnull NotificationItem;
@property (nonatomic, copy) NSString * _Nonnull NotificationTask;
@property (nonatomic, copy) NSString * _Nonnull Equipment;
@property (nonatomic, copy) NSString * _Nonnull FunctionalLocation;
@property (nonatomic, copy) NSString * _Nonnull FormName;
@property (nonatomic, copy) NSString * _Nonnull ApproverID;
@property (nonatomic, copy) NSString * _Nonnull FormStatus;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine19FormAttachmentModel")
@interface FormAttachmentModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull InstanceId;
@property (nonatomic, copy) NSString * _Nonnull FormId;
@property (nonatomic, copy) NSString * _Nonnull Version;
@property (nonatomic, copy) NSString * _Nonnull AttachCounter;
@property (nonatomic, copy) NSString * _Nonnull FileName;
@property (nonatomic, copy) NSString * _Nonnull MimeType;
@property (nonatomic, copy) NSString * _Nonnull Description;
@property (nonatomic, copy) NSString * _Nonnull ObjectNum;
@property (nonatomic, copy) NSString * _Nonnull OperationNum;
@property (nonatomic, copy) NSString * _Nonnull Equipment;
@property (nonatomic, copy) NSString * _Nonnull FunctionalLoc;
@property (nonatomic, copy) NSString * _Nonnull ImageData;
@property (nonatomic, copy) NSString * _Nonnull QuestionId;
@property (nonatomic, copy) NSDate * _Nullable CreatedOn;
@property (nonatomic, copy) NSString * _Nonnull CreatedBy;
@property (nonatomic, copy) NSDate * _Nullable ModifiedOn;
@property (nonatomic, copy) NSString * _Nonnull ModifiedBy;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine23FormMasterMetaDataModel")
@interface FormMasterMetaDataModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull FormName;
@property (nonatomic, copy) NSString * _Nonnull Version;
@property (nonatomic, copy) NSString * _Nonnull FormID;
@property (nonatomic, copy) NSString * _Nonnull CreatedBy;
@property (nonatomic) BOOL Active;
@property (nonatomic, copy) NSString * _Nonnull Category;
@property (nonatomic) BOOL multiOccur;
@property (nonatomic) BOOL mandatory;
@property (nonatomic) NSInteger occur;
@property (nonatomic, copy) NSString * _Nonnull FormCategory;
@property (nonatomic, copy) NSString * _Nonnull FunctionalArea;
@property (nonatomic, copy) NSString * _Nonnull SubArea;
@property (nonatomic, copy) NSString * _Nonnull Description;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine15FormMasterModel")
@interface FormMasterModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull FormID;
@property (nonatomic, copy) NSString * _Nonnull Version;
@property (nonatomic, copy) NSString * _Nonnull CodeGroup;
@property (nonatomic, copy) NSString * _Nonnull FormName;
@property (nonatomic, copy) NSString * _Nonnull Description;
@property (nonatomic, copy) NSString * _Nonnull FormData;
@property (nonatomic, copy) NSString * _Nonnull FormHTML;
@property (nonatomic, copy) NSString * _Nonnull FormModel;
@property (nonatomic) BOOL Active;
@property (nonatomic, copy) NSString * _Nonnull Theme;
@property (nonatomic, copy) NSString * _Nonnull Stylesheet;
@property (nonatomic, copy) NSDate * _Nullable CreatedOn;
@property (nonatomic, copy) NSString * _Nonnull CreatedBy;
@property (nonatomic, copy) NSDate * _Nullable ModifiedOn;
@property (nonatomic, copy) NSString * _Nonnull ModifiedBy;
@property (nonatomic, copy) NSString * _Nonnull Category;
@property (nonatomic, copy) NSString * _Nonnull FunctionalArea;
@property (nonatomic, copy) NSString * _Nonnull SubArea;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine17FormMetaDataModel")
@interface FormMetaDataModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull InstanceId;
@property (nonatomic, copy) NSString * _Nonnull Submitted;
@property (nonatomic, copy) NSString * _Nonnull FormId;
@property (nonatomic, copy) NSString * _Nonnull MultipleSub;
@property (nonatomic, copy) NSString * _Nonnull Version;
@property (nonatomic, copy) NSString * _Nonnull WoNum;
@property (nonatomic, copy) NSString * _Nonnull OrderType;
@property (nonatomic, copy) NSString * _Nonnull ResponseData;
@property (nonatomic, copy) NSString * _Nonnull FormHtml;
@property (nonatomic, copy) NSString * _Nonnull FormModel;
@property (nonatomic, copy) NSString * _Nonnull Occurances;
@property (nonatomic, copy) NSDate * _Nullable CreatedOn;
@property (nonatomic, copy) NSString * _Nonnull CreatedBy;
@property (nonatomic, copy) NSString * _Nonnull IsDraft;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine22FormQuestionImageModel")
@interface FormQuestionImageModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull Formid;
@property (nonatomic, copy) NSString * _Nonnull Version;
@property (nonatomic, copy) NSString * _Nonnull Question;
@property (nonatomic, copy) NSString * _Nonnull FileName;
@property (nonatomic, copy) NSString * _Nonnull MediaType;
@property (nonatomic, copy) NSString * _Nonnull Base64;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine31FormResponseApprovalStatusModel")
@interface FormResponseApprovalStatusModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull FormID;
@property (nonatomic, copy) NSString * _Nonnull Version;
@property (nonatomic, copy) NSString * _Nonnull FormInstanceID;
@property (nonatomic, copy) NSString * _Nonnull ApproverID;
@property (nonatomic, copy) NSString * _Nonnull FormSubmittedBy;
@property (nonatomic, copy) NSString * _Nonnull Counter;
@property (nonatomic, copy) NSString * _Nonnull FormContentStatus;
@property (nonatomic, copy) NSString * _Nonnull Remarks;
@property (nonatomic, copy) NSDate * _Nullable CreatedDate;
@property (nonatomic, strong) SODataDuration * _Nonnull CreatedTime;
@property (nonatomic, copy) NSString * _Nonnull FormName;
@property (nonatomic, copy) NSString * _Nonnull IterationRequired;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine24FormResponseCaptureModel")
@interface FormResponseCaptureModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull InstanceID;
@property (nonatomic, copy) NSString * _Nonnull FormID;
@property (nonatomic, copy) NSString * _Nonnull Version;
@property (nonatomic, copy) NSString * _Nonnull WoNum;
@property (nonatomic, copy) NSString * _Nonnull OperationNum;
@property (nonatomic, copy) NSString * _Nonnull TaskListType;
@property (nonatomic, copy) NSString * _Nonnull Group;
@property (nonatomic, copy) NSString * _Nonnull GroupCounter;
@property (nonatomic, copy) NSString * _Nonnull InternalCounter;
@property (nonatomic, copy) NSString * _Nonnull Equipment;
@property (nonatomic, copy) NSString * _Nonnull FunctionLocation;
@property (nonatomic, copy) NSString * _Nonnull ResponseData;
@property (nonatomic, copy) NSDate * _Nullable CreatedOn;
@property (nonatomic, copy) NSString * _Nonnull CreatedBy;
@property (nonatomic, copy) NSDate * _Nullable ModifiedOn;
@property (nonatomic, copy) NSString * _Nonnull ModifiedBy;
@property (nonatomic, copy) NSString * _Nonnull IsDraft;
@property (nonatomic, copy) NSString * _Nonnull NonObjType;
@property (nonatomic, copy) NSString * _Nonnull OrderType;
@property (nonatomic, copy) NSString * _Nonnull Counter;
@property (nonatomic, copy) NSString * _Nonnull Remarks;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine25FormReviewerResponseModel")
@interface FormReviewerResponseModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull InstanceID;
@property (nonatomic, copy) NSString * _Nonnull FormID;
@property (nonatomic, copy) NSString * _Nonnull Version;
@property (nonatomic, copy) NSString * _Nonnull WoNum;
@property (nonatomic, copy) NSString * _Nonnull OperationNum;
@property (nonatomic, copy) NSString * _Nonnull TaskListType;
@property (nonatomic, copy) NSString * _Nonnull Group;
@property (nonatomic, copy) NSString * _Nonnull GroupCounter;
@property (nonatomic, copy) NSString * _Nonnull InternalCounter;
@property (nonatomic, copy) NSString * _Nonnull Equipment;
@property (nonatomic, copy) NSString * _Nonnull FunctionLocation;
@property (nonatomic, copy) NSString * _Nonnull ResponseData;
@property (nonatomic, copy) NSDate * _Nullable CreatedOn;
@property (nonatomic, copy) NSString * _Nonnull CreatedBy;
@property (nonatomic, copy) NSDate * _Nullable ModifiedOn;
@property (nonatomic, copy) NSString * _Nonnull ModifiedBy;
@property (nonatomic, copy) NSString * _Nonnull IsDraft;
@property (nonatomic, copy) NSString * _Nonnull NonObjType;
@property (nonatomic, copy) NSString * _Nonnull OrderType;
@property (nonatomic, copy) NSString * _Nonnull Counter;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine18FormWorkOrderModel")
@interface FormWorkOrderModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull WorkOrderNumber;
@property (nonatomic, copy) NSString * _Nonnull OrderType;
@property (nonatomic, copy) NSString * _Nonnull Description;
@property (nonatomic, copy) NSString * _Nonnull FormSet;
@property (nonatomic, copy) NSString * _Nonnull FormMetaDataSet;
@property (nonatomic, strong) SODataEntityDefault * _Nonnull entity;
@property (nonatomic, strong) SODataV4_EntityValue * _Nonnull entityValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine22FormsBatchRequestModel")
@interface FormsBatchRequestModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine23FormsFormateHelperClass")
@interface FormsFormateHelperClass : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11FormsEngine10HtmlHelper")
@interface HtmlHelper : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// This class manages a WKWebView. It creates one at init, becomes its navigationDelegate
/// and configures itself as WKScriptMessageHandler.
/// The WKWebView is accessible so its frame can be set by the caller and the view can be added in the hiearchy.
SWIFT_CLASS("_TtC11FormsEngine14WebViewHandler")
@interface WebViewHandler : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WKUserContentController;
@class WKScriptMessage;

@interface WebViewHandler (SWIFT_EXTENSION(FormsEngine)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class WKWebView;
@class WKNavigation;
@class WKNavigationAction;

@interface WebViewHandler (SWIFT_EXTENSION(FormsEngine)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
